#nullable enable

namespace CdpMcp;

/// <summary>RouteOne family gate: OrgansB (intercom..domain) — peel FileLines off Organs.</summary>
internal static partial class CitizenIntentRouter
{
    static Route? TryRouteOrgansB(string raw)
    {
        if (raw.Equals("settings", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("settings ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("options", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("options ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("prefs", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("prefs ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("ide_settings", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("ide_settings ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("tools_options", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("tools_options ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("languages", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("languages ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("languages_page", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("languages_page ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("settings_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("settings_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("settings_page", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("settings_page ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("settings_catalog", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("settings_catalog ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("settings_get", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("settings_get ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("settings_set", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("settings_set ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("settings_unset", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("settings_unset ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("settings_which", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("settings_which ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("options_page", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("options_page ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("lsp_probe", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("lsp_probe ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("lsp_status", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("lsp_status ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("lsp_install", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("lsp_install ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("lsp_ensure", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("lsp_ensure ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("lsp_add", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("lsp_add ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteSettings(raw);
        }

        if (raw.Equals("restore", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("restore ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("restore_previous", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("restore_previous ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("desk_restore", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("desk_restore ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("restore_peek", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("restore_peek ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("recent", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("recent ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("open_recent", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("open_recent ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("recent_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("recent_list ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteRestore(raw);
        }


        if (raw.Equals("intercom", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("intercom ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cide_intercom", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cide_intercom ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("intercom_send", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("intercom_send ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("intercom_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("intercom_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("intercom_ack", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("intercom_ack ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("intercom_history", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("intercom_history ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("intercom_presence", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("intercom_presence ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("intercom_inbox", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("intercom_inbox ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteIntercom(raw);
        }

        if (raw.Equals("cide_presentation", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cide_presentation ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cide_presentation_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cide_presentation_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cide_presentation_set", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cide_presentation_set ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cide_presentation_get", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cide_presentation_get ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("presentation", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("presentation ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("presentation_set", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("presentation_set ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("presentation_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("presentation_scene ", StringComparison.OrdinalIgnoreCase))
        {
            return RoutePresentation(raw);
        }

        if (raw.Equals("toolchain", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("toolchain ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("toolchain_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("toolchain_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_toolchain", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_toolchain ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("toolchain_ensure", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("toolchain_ensure ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("toolchain_probe", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("toolchain_probe ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("toolchain_install", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("toolchain_install ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("toolchain_add", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("toolchain_add ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("toolchain_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("toolchain_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("toolchain_which", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("toolchain_which ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteToolchain(raw);
        }

        if (raw.Equals("cockpit_host", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cockpit_host ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_cockpit_host", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_cockpit_host ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cockpit_start", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cockpit_start ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cockpit_stop", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cockpit_stop ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cockpit_host_start", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cockpit_host_start ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cockpit_host_stop", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cockpit_host_stop ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cockpit_host_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cockpit_host_scene ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteCockpitHost(raw);
        }

        if (raw.Equals("qrh", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("qrh ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("eqrh", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("eqrh ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_qrh", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_qrh ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("qrh_open", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("qrh_open ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("qrh_search", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("qrh_search ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("qrh_index", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("qrh_index ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("qrh_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("qrh_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("qrh_shelf", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("qrh_shelf ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("qrh_related", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("qrh_related ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("eqrh_open", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("eqrh_open ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("eqrh_search", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("eqrh_search ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("eqrh_index", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("eqrh_index ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_qrh_open", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_qrh_open ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_qrh_search", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_qrh_search ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_qrh_index", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_qrh_index ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteQrh(raw);
        }

        if (raw.Equals("webcam", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_webcam", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_webcam ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_frame", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_frame ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_burst", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_burst ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_av", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_av ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_screen", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_screen ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_window_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_window_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_window", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_window ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_audio", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_audio ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_transcribe", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_transcribe ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_ocr", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_ocr ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("webcam_analyze", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("webcam_analyze ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_webcam_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_webcam_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_webcam_frame", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_webcam_frame ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_webcam_window_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_webcam_window_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_webcam_window", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_webcam_window ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteWebcam(raw);
        }

        if (raw.Equals("evidence", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("evidence ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_evidence", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_evidence ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("evidence_build", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("evidence_build ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("evidence_test", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("evidence_test ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("evidence_publish", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("evidence_publish ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("evidence_shell", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("evidence_shell ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("evidence_csx", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("evidence_csx ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("evidence_generic", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("evidence_generic ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("evidence_auto", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("evidence_auto ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_evidence_build", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_evidence_build ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_evidence_test", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_evidence_test ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_evidence_publish", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_evidence_publish ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_evidence_shell", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_evidence_shell ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_evidence_csx", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_evidence_csx ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteEvidence(raw);
        }

        if (raw.Equals("domain", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("domain ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("domain_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("domain_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_domain", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_domain ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("domain_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("domain_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("domain_pulse", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("domain_pulse ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("domain_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("domain_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("domain_card", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("domain_card ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_domain_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_domain_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_domain_pulse", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_domain_pulse ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_domain_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_domain_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_domain_card", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_domain_card ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteDomain(raw);
        }

        if (raw.Equals("rules", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("rules ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("rules_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("rules_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("standing", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("standing ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("healthy_agent", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("healthy_agent ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_rules", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_rules ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("rules_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("rules_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("rules_pulse", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("rules_pulse ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("rules_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("rules_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("rules_card", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("rules_card ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_rules_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_rules_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_rules_pulse", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_rules_pulse ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_rules_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_rules_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_rules_card", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_rules_card ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteRules(raw);
        }

        if (IsArchIntent(raw))
            return RouteArch(raw);


        return null;
    }
}
