#nullable enable

namespace CdpMcp;

/// <summary>RouteOne family gate: OrgansA (icm..restore) — peel FileLines off Organs.</summary>
internal static partial class CitizenIntentRouter
{
    static Route? TryRouteOrgansA(string raw)
    {
        if (raw.Equals("icm", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_icm", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_icm ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("command_module", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("command_module ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_aliases", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_aliases ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_map", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_map ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_resolve", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_resolve ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_invoke", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_invoke ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_exec", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_exec ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("icm_run", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("icm_run ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_icm_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_icm_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_icm_aliases", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_icm_aliases ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_icm_resolve", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_icm_resolve ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_icm_invoke", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_icm_invoke ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteIcm(raw);
        }

        if (raw.Equals("files", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("file_manager", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("file_manager ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("fm", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("fm ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_ls", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_ls ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_cd", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_cd ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_up", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_up ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_stat", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_stat ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_tree", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_tree ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_open", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_open ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_text", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_text ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_read", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_read ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_search", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_search ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_roots", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_roots ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("files_clear", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("files_clear ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_cd", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_cd ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_up", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_up ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_stat", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_stat ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_tree", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_tree ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_open", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_open ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_text", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_text ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_search", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_search ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_roots", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_roots ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_files_clear", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_files_clear ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("fm_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("fm_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("fm_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("fm_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("fm_cd", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("fm_cd ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("fm_tree", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("fm_tree ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("fm_open", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("fm_open ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteFiles(raw);
        }

        if (raw.Equals("onboard", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("onboard ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("onboard_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("onboard_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("explore_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("explore_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("explore", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("explore ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_onboard", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_onboard ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("onboard_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("onboard_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("onboard_scan", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("onboard_scan ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("onboard_refresh", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("onboard_refresh ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("onboard_rescan", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("onboard_rescan ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("onboard_clear", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("onboard_clear ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_onboard_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_onboard_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_onboard_scan", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_onboard_scan ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_onboard_clear", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_onboard_clear ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteOnboard(raw);
        }

        if (raw.Equals("peel", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("peel ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("peel_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("peel_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_peel", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_peel ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("peel_preview", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("peel_preview ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("peel_apply", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("peel_apply ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_peel_preview", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_peel_preview ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_peel_apply", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_peel_apply ", StringComparison.OrdinalIgnoreCase))
        {
            return RoutePeel(raw);
        }

        if (raw.Equals("edit_plan", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("edit_plan ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("edit_plan_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("edit_plan_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_edit_plan", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_edit_plan ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("edit_plan_draft", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("edit_plan_draft ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("edit_plan_validate", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("edit_plan_validate ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("edit_plan_preview", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("edit_plan_preview ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("edit_plan_apply", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("edit_plan_apply ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_edit_plan_draft", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_edit_plan_draft ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_edit_plan_validate", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_edit_plan_validate ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_edit_plan_preview", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_edit_plan_preview ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_edit_plan_apply", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_edit_plan_apply ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteEditPlan(raw);
        }

        if (raw.Equals("analysis", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("analysis_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis_desk ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("analysis_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_analysis_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_analysis_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_analysis", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_analysis ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("analysis_map", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis_map ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("analysis_clones", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis_clones ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("analysis_correspondence", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis_correspondence ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("analysis_corr", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis_corr ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("analysis_semantic", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis_semantic ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("analysis_semantic_map", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("analysis_semantic_map ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_analysis_clones", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_analysis_clones ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_analysis_correspondence", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_analysis_correspondence ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("cdp_analysis_semantic", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("cdp_analysis_semantic ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteAnalysis(raw);
        }

        if (raw.Equals("pressure", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pressure ", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pressure op=", StringComparison.OrdinalIgnoreCase))
        {
            return RoutePressure(raw);
        }

        if (raw.Equals("calendar", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("calendar ", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("calendar op=", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("clock", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("clock ", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("clock op=", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("calendar_desk", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("calendar_desk ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteCalendar(raw);
        }

        if (raw.Equals("land", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("land ", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("land op=", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("deep_link", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("deep_link ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("deeplink", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("deeplink ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("land_restore", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("land_restore ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("land_open", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("land_open ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("land_goto", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("land_goto ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("land_show", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("land_show ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("land_go", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("land_go ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteLand(raw);
        }

        if (raw.Equals("pkg", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pkg ", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pkg op=", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("nuget", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("nuget ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("packages", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("packages ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("package", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("package ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("pkg_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pkg_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("pkg_find", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pkg_find ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("pkg_add", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pkg_add ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("pkg_remove", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pkg_remove ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("pkg_update", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pkg_update ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("pkg_outdated", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("pkg_outdated ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("nuget_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("nuget_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("nuget_find", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("nuget_find ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("nuget_add", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("nuget_add ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("nuget_remove", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("nuget_remove ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("nuget_update", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("nuget_update ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("nuget_outdated", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("nuget_outdated ", StringComparison.OrdinalIgnoreCase))
        {
            return RoutePkg(raw);
        }

        if (raw.Equals("project", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("project ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("projects", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("projects ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("project_scene", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("project_scene ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("project_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("project_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("project_create", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("project_create ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("project_close", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("project_close ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("project_add", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("project_add ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("project_add_to_sln", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("project_add_to_sln ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("sln", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("sln ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("solution", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("solution ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("sln_list", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("sln_list ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("sln_create", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("sln_create ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("sln_projects", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("sln_projects ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("sln_add", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("sln_add ", StringComparison.OrdinalIgnoreCase)
            || raw.Equals("sln_remove", StringComparison.OrdinalIgnoreCase)
            || raw.StartsWith("sln_remove ", StringComparison.OrdinalIgnoreCase))
        {
            return RouteProject(raw);
        }


        return null;
    }
}
