#nullable enable
using System.Text.Json;

namespace CdpMcp;

/// <summary>
/// CDS go-verb allowlist (CIDE ADR 0036) — where desk verbs may land; not IDS overlays.
/// </summary>
internal static partial class IdeCockpit
{
    /// <summary>Allowlist desk verbs → organ tools. Cockpit stays a пульт, not the organ.</summary>
    static readonly Dictionary<string, (string Tool, Dictionary<string, JsonElement>? Defaults)> GoMap =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["editor_scene"] = ("cdp_editor_scene", null),
            ["editor"] = ("cdp_editor_scene", null),
            ["edit_draft"] = ("cdp_edit_plan", Dict(("op", "draft"))),
            ["edit_plan"] = ("cdp_edit_plan", Dict(("op", "draft"))),
            ["scope"] = (EditSniper.ToolName, Dict(("op", "scope"))),
            ["target"] = (EditSniper.ToolName, Dict(("op", "target"))),
            ["peek"] = (EditSniper.ToolName, Dict(("op", "peek"))),
            ["scope_clear"] = (EditSniper.ToolName, Dict(("op", "clear"))),
            ["sniper"] = (EditSniper.ToolName, Dict(("op", "status"))),
            ["buffer_scene"] = ("cdp_buffer", Dict(("op", "scene"))),
            ["buffer"] = ("cdp_buffer", Dict(("op", "scene"))),
            ["reload"] = ("cdp_buffer", Dict(("op", "reload"))),
            ["keep_disk"] = ("cdp_buffer", Dict(("op", "keep_disk"))),
            ["disk_peek"] = ("cdp_buffer", Dict(("op", "disk_peek"))),
            ["undo"] = ("cdp_buffer", Dict(("op", "undo"))),
            ["redo"] = ("cdp_buffer", Dict(("op", "redo"))),
            ["history"] = ("cdp_buffer", Dict(("op", "history"))),
            ["copy"] = ("cdp_buffer", Dict(("op", "copy"))),
            ["cut"] = ("cdp_buffer", Dict(("op", "cut"))),
            ["paste"] = ("cdp_buffer", Dict(("op", "paste"))),
            ["put"] = ("cdp_buffer", Dict(("op", "put"))),
            ["dump"] = ("cdp_buffer", Dict(("op", "put"))),
            ["take"] = ("take", null),
            ["get_take"] = ("get_take", null),
            ["ship"] = ("take", null),
            ["share"] = ("cdp_buffer", Dict(("op", "share"))),
            ["paste_sniper"] = ("cdp_buffer", Dict(("op", "paste"), ("sniper", "true"), ("place", "replace"))),
            ["put_sniper"] = ("cdp_buffer", Dict(("op", "put"), ("sniper", "true"), ("place", "replace"))),
            ["clipboard"] = ("cdp_buffer", Dict(("op", "clipboard"))),
            ["clip"] = ("cdp_buffer", Dict(("op", "clipboard"))),
            ["clip_clear"] = ("cdp_buffer", Dict(("op", "clipboard_clear"))),
            ["clipboard_clear"] = ("cdp_buffer", Dict(("op", "clipboard_clear"))),
            ["find"] = ("find", null),
            ["get_find"] = ("get_find", null),
            ["find_all"] = ("find_all", null),
            ["find_in_files"] = ("find_in_files", null),
            ["fif"] = ("find_in_files", null),
            ["find_desk"] = (IdeFindChannel.ToolName, null),
            ["search_desk"] = (IdeFindChannel.ToolName, null),
            ["code_search"] = (IdeFindChannel.ToolName, null),
            ["cdp_search"] = (IdeFindChannel.ToolName, null),
            ["sa_desk"] = (IdeSaChannel.ToolName, null),
            ["refactor_plan"] = (IdeRefactorPlanChannel.ToolName, null),
            ["refactor"] = (IdeRefactorPlanChannel.ToolName, null),
            ["cdp_refactor"] = (IdeRefactorPlanChannel.ToolName, null),
            ["code_sa"] = (IdeSaChannel.ToolName, null),
            ["pre_sa"] = (IdeSaChannel.ToolName, null),
            ["sa_code"] = (IdeSaChannel.ToolName, null),
            ["cdp_sa"] = (IdeSaChannel.ToolName, null),
            ["debug_desk"] = (IdeDebugSaChannel.ToolName, null),
            ["dap_sa"] = (IdeDebugSaChannel.ToolName, null),
            ["debug_sa"] = (IdeDebugSaChannel.ToolName, null),
            ["cdp_debug_sa"] = (IdeDebugSaChannel.ToolName, null),
            ["test_desk"] = (IdeTestSaChannel.ToolName, null),
            ["test_sa"] = (IdeTestSaChannel.ToolName, null),
            ["cdp_test_sa"] = (IdeTestSaChannel.ToolName, null),
            ["build_desk"] = (IdeBuildSaChannel.ToolName, null),
            ["ship_desk"] = (IdeBuildSaChannel.ToolName, null),
            ["build_sa"] = (IdeBuildSaChannel.ToolName, null),
            ["ship_sa"] = (IdeBuildSaChannel.ToolName, null),
            ["cdp_build_sa"] = (IdeBuildSaChannel.ToolName, null),
            ["crm"] = (IdeCrmChannel.ToolName, null),
            ["callout"] = (IdeCrmChannel.ToolName, null),
            ["crm_panel"] = (IdeCrmChannel.ToolName, null),
            ["cdp_crm"] = (IdeCrmChannel.ToolName, null),
            ["arch_desk"] = (IdeArchBoardChannel.ToolName, null),
            ["arch_board"] = (IdeArchBoardChannel.ToolName, null),
            ["board"] = (IdeArchBoardChannel.ToolName, null),
            ["sketch_desk"] = (IdeArchBoardChannel.ToolName, null),
            ["cdp_arch"] = (IdeArchBoardChannel.ToolName, null),
            ["onboard_desk"] = (IdeOnboardChannel.ToolName, null),
            ["explore_desk"] = (IdeOnboardChannel.ToolName, null),
            ["onboard"] = (IdeOnboardChannel.ToolName, null),
            ["explore"] = (IdeOnboardChannel.ToolName, null),
            ["cdp_onboard"] = (IdeOnboardChannel.ToolName, null),
            ["toolchain"] = (IdeToolchainChannel.ToolName, null),
            ["toolchain_desk"] = (IdeToolchainChannel.ToolName, null),
            ["toolchain_ensure"] = (IdeToolchainChannel.ToolName, Dict(("op", "ensure"))),
            ["toolchain_probe"] = (IdeToolchainChannel.ToolName, Dict(("op", "probe"))),
            ["toolchain_install"] = (IdeToolchainChannel.ToolName, Dict(("op", "install"))),
            ["toolchain_add"] = (IdeToolchainChannel.ToolName, Dict(("op", "add"))),
            ["cdp_toolchain"] = (IdeToolchainChannel.ToolName, null),
            ["files_desk"] = (IdeFilesChannel.ToolName, null),
            ["files"] = (IdeFilesChannel.ToolName, null),
            ["explorer"] = (IdeFilesChannel.ToolName, null),
            ["fm"] = (IdeFilesChannel.ToolName, null),
            ["file_manager"] = (IdeFilesChannel.ToolName, null),
            ["cdp_files"] = (IdeFilesChannel.ToolName, null),
            ["ignite_desk"] = (IdeIgniteChannel.ToolName, null),
            ["ignite"] = (IdeIgniteChannel.ToolName, null),
            ["autoignite"] = (IdeIgniteChannel.ToolName, null),
            ["cdt_ignite"] = (IdeIgniteChannel.ToolName, null),
            ["cdp_ignite"] = (IdeIgniteChannel.ToolName, null),
            ["webcam_desk"] = (IdeWebcamChannel.ToolName, null),
            ["webcam"] = (IdeWebcamChannel.ToolName, null),
            ["camera"] = (IdeWebcamChannel.ToolName, null),
            ["sense"] = (IdeWebcamChannel.ToolName, null),
            ["cdp_webcam"] = (IdeWebcamChannel.ToolName, null),
            ["pressure_desk"] = (IdePressureChannel.ToolName, null),
            ["pressure"] = (IdePressureChannel.ToolName, null),
            ["compact_prep"] = (IdePressureChannel.ToolName, null),
            ["pre_compact"] = (IdePressureChannel.ToolName, null),
            ["cdp_pressure"] = (IdePressureChannel.ToolName, null),
            ["replace_all"] = ("cdp_buffer", Dict(("op", "replace_all"))),
            ["back"] = ("cdp_buffer", Dict(("op", "back"))),
            ["forward"] = ("cdp_buffer", Dict(("op", "forward"))),
            ["recent_files"] = ("cdp_buffer", Dict(("op", "recent_files"))),
            ["scratch"] = ("cdp_buffer", Dict(("op", "scratch"))),
            ["git_scene"] = ("git_git_scene", null),
            ["git"] = ("git_git_scene", null),
            ["git_draft"] = ("git_git_plan", Dict(("op", "draft"))),
            ["git_plan"] = ("git_git_plan", Dict(("op", "draft"))),
            ["test_scene"] = ("cdp_test_scene", null),
            ["test"] = ("cdp_test_scene", null),
            ["test_plan"] = ("cdp_test_plan", Dict(("op", "preview"))),
            ["analysis_scene"] = ("cdp_analysis_scene", null),
            ["analysis"] = ("cdp_analysis_scene", null),
            ["clones"] = ("cdp_analysis_scene", Dict(("feature", "clones"))),
            ["correspondence"] = ("cdp_analysis_scene", Dict(("feature", "correspondence"))),
            ["corr"] = ("cdp_analysis_scene", Dict(("feature", "correspondence"))),
            ["semantic_map"] = ("cdp_analysis_scene", Dict(("feature", "semantic_map"))),
            ["semantic"] = ("cdp_analysis_scene", Dict(("feature", "semantic_map"))),
            ["related"] = ("cdp_analysis_scene", Dict(("feature", "semantic_map"))),
            ["complete"] = ("get_completions", null),
            ["completions"] = ("get_completions", null),
            ["intellisense"] = ("get_completions", null),
            ["signature_help"] = ("get_signature_help", null),
            ["sighelp"] = ("get_signature_help", null),
            ["script_scene"] = ("cdp_script_scene", null),
            ["script"] = ("cdp_script_scene", null),
            ["script_put"] = ("cdp_script_scene", Dict(("op", "put"))),
            ["script_open"] = ("cdp_script_scene", Dict(("op", "open"))),
            ["script_check"] = ("cdp_script_scene", Dict(("op", "check"))),
            ["script_run"] = ("cdp_script_scene", Dict(("op", "run"))),
            ["script_last"] = ("cdp_script_scene", Dict(("op", "last"))),
            ["script_help"] = ("cdp_script_scene", Dict(("op", "help"))),
            ["goto"] = ("cdp_goto", null),
            ["go_to"] = ("cdp_goto", null),
            ["t"] = ("cdp_goto", null),
            // Goto Feature (code nav) — not Task Manager; TM uses soft organ + plan aliases.
            ["q"] = ("cdp_goto", Dict(("kind", "feature"))),
            ["goto_feature"] = ("cdp_goto", Dict(("kind", "feature"))),
            ["shell_scene"] = ("cdp_shell_scene", null),
            ["shell"] = ("cdp_shell_scene", null),
            ["shell_last"] = ("cdp_shell_last", null),
            ["debug_scene"] = ("cdp_debug", Dict(("op", "scene"))),
            ["debug"] = ("cdp_debug", Dict(("op", "scene"))),
            ["build"] = ("cdp_build", null),
            ["project_scene"] = ("cdp_project_scene", null),
            ["project"] = ("cdp_project_scene", null),
            // Plan = Task Manager organ (Feature/Task vocabulary). work/tasks/tm = aliases.
            ["plan"] = ("cdp_work", Dict(("op", "tasks"))),
            ["work"] = ("cdp_work", Dict(("op", "tasks"))),
            ["tasks"] = ("cdp_work", Dict(("op", "tasks"))),
            ["task"] = ("cdp_work", Dict(("op", "tasks"))),
            ["feature"] = ("cdp_work", Dict(("op", "tasks"))),
            ["tm"] = ("cdp_work", Dict(("op", "tasks"))),
            ["restore"] = ("cdp_restore", null),
            ["restore_previous"] = ("cdp_restore", null),
            ["previous"] = ("cdp_restore", null),
            ["desk_restore"] = ("cdp_restore", null),
            ["deploy"] = ("cdp_deploy", null),
            ["hard_deploy"] = ("cdp_deploy", Dict(("mode", "hard"))),
            ["soft_deploy"] = ("cdp_deploy", Dict(("mode", "soft"))),
            ["navigate"] = ("cdp_land", null),
            ["land"] = ("cdp_land", null),
            ["deep_link"] = ("cdp_land", null),
            ["deeplink"] = ("cdp_land", null),
            ["mcp_scene"] = ("cdp_mcp", Dict(("op", "scene"))),
            ["mcp"] = ("cdp_mcp", Dict(("op", "scene"))),
            ["mcp_presets"] = ("cdp_mcp", Dict(("op", "presets"))),
            ["mcp_mount"] = ("cdp_mcp", Dict(("op", "mount"))),
            ["mcp_tools"] = ("cdp_mcp", Dict(("op", "tools"))),
            ["mcp_call"] = ("cdp_mcp", Dict(("op", "call"))),
            ["mcp_unmount"] = ("cdp_mcp", Dict(("op", "unmount"))),
            ["scene_internet_browser"] = ("cdp_browser", Dict(("op", "scene"))),
            ["internet_browser"] = ("cdp_browser", Dict(("op", "scene"))),
            ["internet_browser_scene"] = ("cdp_browser", Dict(("op", "scene"))),
            ["browser_scene"] = ("cdp_browser", Dict(("op", "scene"))),
            ["browser"] = ("cdp_browser", Dict(("op", "scene"))),
            ["internet_browser_open"] = ("cdp_browser", Dict(("op", "open"))),
            ["internet_browser_dump"] = ("cdp_browser", Dict(("op", "dump"))),
            ["internet_browser_links"] = ("cdp_browser", Dict(("op", "links"))),
            ["internet_browser_follow"] = ("cdp_browser", Dict(("op", "follow"))),
            ["internet_browser_which"] = ("cdp_browser", Dict(("op", "which"))),
            ["internet_browser_search"] = ("cdp_browser", Dict(("op", "search"))),
            ["search"] = ("cdp_browser", Dict(("op", "search"))),
            ["settings"] = ("cdp_settings", Dict(("op", "options"))),
            ["settings_scene"] = ("cdp_settings", Dict(("op", "options"))),
            ["ide_settings"] = ("cdp_settings", Dict(("op", "options"))),
            ["prefs"] = ("cdp_settings", Dict(("op", "options"))),
            ["options"] = ("cdp_settings", Dict(("op", "options"))),
            ["tools_options"] = ("cdp_settings", Dict(("op", "options"))),
            ["options_page"] = ("cdp_settings", Dict(("op", "page"))),
            ["settings_page"] = ("cdp_settings", Dict(("op", "page"))),
            ["settings_catalog"] = ("cdp_settings", Dict(("op", "catalog"))),
            ["settings_get"] = ("cdp_settings", Dict(("op", "get"))),
            ["settings_set"] = ("cdp_settings", Dict(("op", "set"))),
            ["settings_unset"] = ("cdp_settings", Dict(("op", "unset"))),
            ["settings_which"] = ("cdp_settings", Dict(("op", "which"))),
            ["lsp_probe"] = ("cdp_settings", Dict(("op", "lsp_probe"))),
            ["lsp_status"] = ("cdp_settings", Dict(("op", "lsp_probe"))),
            ["lsp_install"] = ("cdp_settings", Dict(("op", "lsp_install"))),
            ["lsp_ensure"] = ("cdp_settings", Dict(("op", "lsp_ensure"))),
            ["lsp_add"] = ("cdp_settings", Dict(("op", "lsp_add"))),
            ["languages"] = ("cdp_settings", Dict(("op", "page"), ("page", "languages"))),
            ["languages_page"] = ("cdp_settings", Dict(("op", "page"), ("page", "languages"))),
        };

    static Dictionary<string, JsonElement> Dict(params (string Key, string Value)[] pairs)
    {
        var d = new Dictionary<string, JsonElement>(StringComparer.Ordinal);
        foreach (var (k, v) in pairs)
            d[k] = JsonSerializer.SerializeToElement(v);
        return d;
    }
}


