using System.Text.Json;
using Cdp.Core;
using TerminalMcp.Core;

namespace CdpMcp;

/// <summary>KeySpec catalog (≤ADX soft-warn peel).</summary>
internal sealed partial class IdeSettingsHabitat
{
    static IEnumerable<KeySpec> Specs(CdpSettings p, string configPath)
    {
        var layouts = IdeCockpit.LayoutPresetIds;
        var mcpPresets = McpOutletHabitat.KnownPresetIds;
        return
        [
            new("session.default_phase", "environment", "session", "Default phase", "enum",
                ["recall", "explore", "clarify", "plan", "act", "verify", "handoff"],
                "user", true, true, false,
                "Cold/hot session phase (ListTools catalog axis)", p.DefaultPhase, p.DefaultPhase),
            new("session.default_object", "environment", "session", "Default object", "enum",
                ["kb", "code", "repo", "task", "finding", "process", "issue", "session"],
                "user", true, true, false,
                "Cold/hot session object", p.DefaultObject, p.DefaultObject),
            new("browser.search_engine", "internet", "browser", "Default search engine", "enum",
                ["ddg", "google", "bing"],
                "user", true, true, false,
                "op=search without engine= (sovereign default = ddg)", "ddg", null),
            new("browser.user_agent", "internet", "browser", "User-Agent", "string", null,
                "user", true, true, false,
                "Lynx -useragent= (env CDP_BROWSER_UA wins if set)",
                InternetBrowserHabitat.DefaultUserAgent, null),
            new("browser.width", "internet", "browser", "Dump width", "int", null,
                "user", true, true, false,
                "Lynx -width", InternetBrowserHabitat.DefaultWidth.ToString(), null),
            new("browser.timeout_seconds", "internet", "browser", "Fetch timeout", "int", null,
                "user", true, true, false,
                "Seconds", InternetBrowserHabitat.DefaultTimeoutSeconds.ToString(), null),
            new("browser.dump_chars", "internet", "browser", "Dump char cap", "int", null,
                "user", true, true, false,
                "Max body chars returned", InternetBrowserHabitat.DumpBodyChars.ToString(), null),
            new("desk.mode", "desk", "desk", "Desk model", "enum",
                ["seats", "tiles"],
                "user", true, true, false,
                "seats = Scan Pattern P|Forward|M (default); tiles = legacy append pins", "seats", null),
            new("desk.default_layout", "desk", "desk", "Default seat/tile preset", "enum", layouts,
                "user", true, true, false,
                "Cold fill when seats empty (cockpit = P+F+M)", null, null),
            new("desk.layout.hold", "desk", "desk", "Hold phase→desk auto-layout", "bool", null,
                "user", true, true, false,
                "When true, cdp_context phase= does not retune seats (escape). Explicit layout= still works.", "false", null),
            new("desk.default_mfd", "desk", "desk", "Default MFD (deprecated)", "enum",
                ["nav", "sys", "chk", "ecl", "gates"],
                "user", true, true, false,
                "Deprecated in seats: use go=sys|chk|gates or desk_detail=nav. Kept for tiles/legacy.", "nav", null),
            new("desk.seat.p", "desk", "desk", "Default P seat organ", "string", null,
                "user", true, true, false,
                "Cold P when no layout (project_scene|empty)", "project_scene", null),
            new("desk.seat.forward", "desk", "desk", "Default Forward seat organ", "string", null,
                "user", true, true, false,
                "Cold Forward (editor_scene)", "editor_scene", null),
            new("desk.seat.m", "desk", "desk", "Default M seat organ", "string", null,
                "user", true, true, false,
                "Cold M (browser|empty)", "browser", null),
            new("desk.seat.organ.browser", "desk", "desk", "Seat for browser", "enum",
                ["p", "forward", "m"],
                "user", true, true, false,
                "Override organ→seat policy", "m", null),
            new("desk.seat.organ.git", "desk", "desk", "Seat for git", "enum",
                ["p", "forward", "m"],
                "user", true, true, false,
                "Override organ→seat policy", "m", null),
            new("desk.seat.organ.shell", "desk", "desk", "Seat for shell", "enum",
                ["p", "forward", "m"],
                "user", true, true, false,
                "Override organ→seat policy", "m", null),
            new("desk.seat.organ.correspondence", "desk", "desk", "Seat for correspondence", "enum",
                ["p", "forward", "m"],
                "user", true, true, false,
                "Override organ→seat policy", "m", null),
            new("desk.seat.organ.editor_scene", "desk", "desk", "Seat for editor", "enum",
                ["p", "forward", "m"],
                "user", true, true, false,
                "Override organ→seat policy", "forward", null),
            new("shell.timeout_seconds", "shell", "shell", "Command timeout", "int", null,
                "user", true, true, false,
                "cdp_shell_run default timeout", ShellHabitat.DefaultTimeoutSeconds.ToString(), null),
            new("shell.codepage", "shell", "shell", "Console codepage", "int", null,
                "user", true, true, false,
                "Default tab codepage (65001 = UTF-8)", "65001", null),
            new("mcp.default_preset", "mcp", "mcp", "Default mount preset", "enum", mcpPresets,
                "user", true, true, false,
                "cdp_mcp op=mount with no preset=/command= uses this", null, null),
            new("process.default_phase", "process", "process", "toml default_phase", "string", null,
                "process", false, false, true, "Startup phase", p.DefaultPhase, p.DefaultPhase),
            new("process.default_object", "process", "process", "toml default_object", "string", null,
                "process", false, false, true, "Startup object", p.DefaultObject, p.DefaultObject),
            new("process.memory.world.enabled", "process", "process", "memory.world", "bool", null,
                "process", false, false, true, "Backend toggle", BoolStr(p.Memory.World.Enabled), BoolStr(p.Memory.World.Enabled)),
            new("process.memory.project.enabled", "process", "process", "memory.project", "bool", null,
                "process", false, false, true, "Backend toggle", BoolStr(p.Memory.Project.Enabled), BoolStr(p.Memory.Project.Enabled)),
            new("process.memory.session.enabled", "process", "process", "memory.session", "bool", null,
                "process", false, false, true, "Backend toggle", BoolStr(p.Memory.Session.Enabled), BoolStr(p.Memory.Session.Enabled)),
            new("process.dev.git.enabled", "process", "process", "git", "bool", null,
                "process", false, false, true, "Backend toggle", BoolStr(p.Dev.Git.Enabled), BoolStr(p.Dev.Git.Enabled)),
            new("process.dev.debug.enabled", "process", "process", "debug", "bool", null,
                "process", false, false, true, "Backend toggle", BoolStr(p.Dev.Debug.Enabled), BoolStr(p.Dev.Debug.Enabled)),
            new("process.languages", "process", "process", "Languages", "string", null,
                "process", false, false, true, "Language ids", string.Join(",", p.Languages.Ids), string.Join(",", p.Languages.Ids)),
            new("process.config_path", "process", "process", "Config path", "string", null,
                "process", false, false, true, "Resolved cdp-mcp.toml", configPath, configPath),
        ];
    }
}
